version: '3'
services:
  nginx:
    image: dyladan/nginx-alpine-debug:latest
    container_name: ng01
    ports:
      - "443:443"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - ./config:/config
      - ./src/static:/static
    depends_on:
      - "web"

  web:
    build: .
    container_name: web01
    command: bash -c "python manage.py makemigrations dtags && python manage.py migrate && gunicorn dtags.wsgi -b 0.0.0.0:443"
    depends_on:
      - "db"
    volumes:
      - ./src:/src
      - ./static:/static
    expose:
      - "8000"

  db:
    image: postgres:latest
    container_name: db01
    ports:
      - "5432:5432"
